### ISSUE TITLE
Add config to switch if we want SQLight3 or YAML

### ISSUE THREAD

**Issue by ghost** [fujiwaraizuho/LoginSystem#1]

**Comment by fujiwaraizuho** [comment]
Thank you for your post. Please tell me a bit more.

**Comment by ghost** [comment]
Why not if you can use it in a config.yml choose if we wanted to use a database SQLite3 or-well YAML

**Comment by fujiwaraizuho** [comment]
Is that to make data saving method selectable for SQLite3 and YAML?

**Comment by ghost** [comment]
Yes

**Comment by fujiwaraizuho** [comment]
Sorry... What are the merits of saving in YAML?
